### ISSUE TITLE
Memory Leak on using Jest Circus as the Test-Runner

### ISSUE THREAD

**Issue by sauravhiremath** [MLH-Fellowship/jest#19]
## Where did the memory leak originate?
![mem-leak](https://user-images.githubusercontent.com/28642011/86291989-8d555d00-bc0d-11ea-8965-f2b1115ffe86.png)

## How to reproduce the issue?

```
// Checkout PR 18
git fetch origin pull/18/head:individual-test-report

// Clean your yarn builds and re-build again
yarn clean-all
yarn

//Run this to reproduce the issue
JEST_CIRCUS=1 yarn test-leak
```

## How does the "memory leak test fail" look?

```typescript
    Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (packages/jest-core/build/TestScheduler.js:190:18)
          at Array.map (<anonymous>)
```

**Comment by kunal-kushwaha** [comment]
Reference: https://github.com/MLH-Fellowship/jest/pull/6

**Comment by SimenB** [comment]
I won't have time to look into this properly until the weekend/next week, but `jest-circus` has _always_ failed the `test-leak` script up until https://github.com/facebook/jest/pull/9934 landed a couple of months ago. So I'd try to make sure you're rebased on top of master, and then try to do a bisect of all the commits on top of that.

**Comment by sauravhiremath** [comment]
This is a rough draft of how I traced the mem-leak. Will edit it later for a cleaner one

TestCaseReporterHandler.ts [sendMessageToJest(‘test-case-result’, testCaseResult)] -> TestRunner -> EventEmiiter.on(‘test-case-result’, (testCaseResult)) ->TestScheduler (onTestCaseResult) -> ReporterDispatcher (onTestCaseResult) -> default_reporter (onTestCaseResult) -> Status (addTestCaseResult())

Here, `TestCaseReporterHandler` emits `test-case-result`, but here it passes down the array reference and not a copy of array. Hence in all the flow mentioned above, the reference still persists causing `testCaseResult` to be present globally for all workers spawned.

This was avoided down the lane, in Status function by making a `deepCyclicCopy` of the array passed. Hence removing the global reference of the array once and for all, that too for all spawned workers
