### ISSUE TITLE
Redundant typeof check 

### ISSUE THREAD

**Issue by kunal-kushwaha** [MLH-Fellowship/jest#3]
Redundant typeof check in jest-cli/src/cli/index.ts in readResultsAndExit 
https://github.com/MLH-Fellowship/jest/blob/a35b9cc686e542064d6622dd1886c13a509465f5/packages/jest-cli/src/cli/index.ts#L121

Not a major issue, feedback required

**Comment by sauravhiremath** [comment]
@kunal-kushwaha Yeah, it does seem to do a redundant check here. We can include this fix too, in the main PR #6 

```typescript
// Here testFailureExitCode has type as number
const code = !result || result.success ? 0 : globalConfig.testFailureExitCode;

// ✗✗ The typeof code === 'number' check looks redundant to me, as explained above ✗✗
if (typeof code === 'number' && code !== 0) { ... }
```
