### ISSUE TITLE
Functions do not exist when trying importing types from @jest/globals

### ISSUE THREAD

**Issue by smartclash** [MLH-Fellowship/jest#34]
We're just copying the types test from [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/jest-tests.ts) and making changes to it so that TSD can do the type checks.

As discussed in Discord with Simen, I started using types from `@jest/globals` for every function like `expect`, `it`, `test`... etc. as you can see it [here](https://github.com/MLH-Fellowship/jest/blob/881dfca83c158bc97f06cf7cca37b68f82f27916/test-types/it.test.ts#L6-L7)

Though we are copying the types test written already in DefinitelyTyped, we are still getting weird errors like...

***Does not exist***

- Property 'only' does not exist on type `ItBase & { concurrent?: ItConcurrentBase | undefined; }`
![Screenshot from 2020-08-17 11-18-38](https://user-images.githubusercontent.com/16922883/90361291-719dfd00-e07b-11ea-98e8-4392bd36e0b3.png)

- Cannot invoke an object which is possibly `undefined`.
![Screenshot from 2020-08-17 11-20-00](https://user-images.githubusercontent.com/16922883/90361361-a0b46e80-e07b-11ea-961f-ee313ffd49f7.png)

***Argument errors***

- Argument of type `0` is not assignable to parameter of type `string`.
- Argument of type `{ name: string; }` is not assignable to parameter of type `string`.
![Screenshot from 2020-08-17 11-22-54](https://user-images.githubusercontent.com/16922883/90361507-099be680-e07c-11ea-9d21-97d3547da145.png)

These are just three errors of many of same kind.

**Comment by SimenB** [comment]
> * Property 'only' does not exist on type `ItBase & { concurrent?: ItConcurrentBase | undefined; }`

That seems correct - `fit.only` is essentially `it.only.only` which is not valid

> * Cannot invoke an object which is possibly `undefined`.

That's a bug in Jest, it should not be `undefined`

> Argument errors

All of those look correct, only valid first argument to `describe` is a `string`. We should have some `expectError` or something, tho 🙂
