### ISSUE TITLE
Integrate a runner and reporter for testing types

### ISSUE THREAD

**Issue by smartclash** [MLH-Fellowship/jest#4]
## Summary 
Type definitions help ensure your code is correct, but it’s also very useful to ensure your types are correct, especially if you ship types with your library. Ensuring that you get type errors where you expect is also useful, so your types don’t regress in functionality by accident. Being able to test your types next to your logic, with much the same API, will make it easier for people to maintain high quality type definitions.
This will help APIs injected into a test by Jest are well typed. 

## Test Plan
 - This can be tackled by making a [custom runner]() that will just extend [SamVerschueren/tsd](https://github.com/SamVerschueren/tsd) inside.
  - `tsd` essentially runs the typescript compiler and injects assertions, which can be added in a custom runner which will run part of Jest's test suite
 - The issue is targeted towards "write tests for Jest's own types" rather than "create a typings test runner"
 - Assert type tests for `expect` and different `jest` objects like `jest.mock`, etc
 - Assertions that invalid things are reported as type errors would be great.

## Todos
- [x] Basic Scaffolding
- [ ] Integrate TSD 
  - There are techniques like `const a: import("jest").Expect` which would allow types to be passed around internally without too much churn
- [ ] Write tests for this runner
- [ ] Update the documentation (and CHANGELOG.md)

## References
- Current test suite in DefinitelyTyped types: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/jest-tests.ts
- TSD: https://github.com/SamVerschueren/tsd
- Custom Runner: https://jestjs.io/docs/en/configuration#runner-string

**Comment by smartclash** [comment]
Could probably draw inspiration from [`jest-runner-prettier`](https://github.com/keplersj/jest-runner-prettier)

**Comment by kunal-kushwaha** [comment]
@sauravhiremath @jevakallio @smartclash I have updated the Summary, Todos and Test Plan. Feedback required 👍

**Comment by smartclash** [comment]
Since this issue is more of having to make a custom runner, we'll be making this as a separate project. Integrating it inside Jest itself could be a bad idea.

You can follow the development of this runner at https://github.com/MLH-Fellowship/jest-runner-tsd/

**Comment by kunal-kushwaha** [comment]
I agree

**Comment by SimenB** [comment]
Sorry I never got back to this - the plan looks great!

**Comment by smartclash** [comment]
The underlying library (TSD) that we are planning to import needs some stuffs to be fixed. So, a fork has been made at https://github.com/MLH-Fellowship/tsd. They'll be fixed and we will be opening a PR to the origin. After it is merged it'll be used in custom runner that we are making.

**Comment by smartclash** [comment]
Final work plan:

We'll be having a separate config file for jest, something like `jest.config.types.js` which will use the custom runner we are making ([jest-runner-tsd](https://github.com/MLH-Fellowship/jest-runner-tsd)).

We'll also be adding a script inside `package.json` so that we can test types by running `yarn test-types` which would basically run jest with the `jest.config.types.js` config.

About where to place the type definition test files, I think it would be great to place them under `__tests__` folder of each package and name the file as `types.test.ts`.

Or we can have a new folder inside `__tests__` something like `types` and place multiple test files inside the types folder.

Let me know which one is the better approach or if you have something better.

No matter which approach, we have to configure `testRegex` option to make it correctly find the test files.

**References**:
- [Forked TSD](https://github.com/MLH-Fellowship/tsd/)
- [`jest-runner-tsd`](https://github.com/MLH-Fellowship/jest-runner-tsd)

**Comment by SimenB** [comment]
If the PRs take time landing in upstream `tsd` I vote for publishing a fork and using that in the runner to unblock work in landing this in Jest. Should be simple enough to switch back to mainline once `tsd` is updated 🙂
